### ISSUE TITLE
Testing equality in case expressions

### ISSUE THREAD

**Issue by gwaerondor** [lpil/gleam#253] opened 2019-09-20 02:21 UTC
It would be handy to be able to do pattern matches for equality by using the same variable name in a single pattern match, just like in Erlang.

```
pub fn are_equal(p: Pair(a, a)) -> Bool {
  case p {
    | Pair(x, x) -> True
    | Pair(_, _) -> False
  }
}
```

But this is compiled into erlang code:
```erlang
are_equal(P) ->
    case P of
        {X, X1} -> true;
        {_, _} -> false
    end.
```

so the first clause always matches (and compiles with warnings that X and X1 are unused).

**Comment by lpil** [comment] 2019-09-20 09:57
Ah, closing as a duplicate of https://github.com/lpil/gleam/issues/225

Thanks!

**Closed by lpil** 2019-09-20 09:57 UTC
Labels: area:compiler, help wanted
